//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_Pixel_Art.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_Pixel_Art.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white_concrete #d0d6d7
        ///orange_concrete #df6000
        ///magenta_concrete #a9309f
        ///light_blue_concrete #2389c7
        ///yellow_concrete #f1af15
        ///lime_concrete #5faa1a
        ///pink_concrete #d5648e
        ///gray_concrete #36393d
        ///light_gray_concrete #36393d
        ///cyan_concrete #157687
        ///purple_concrete #65209d
        ///blue_concrete #2d2f90
        ///brown_concrete #603b1f
        ///green_concrete #4a5c25
        ///red_concrete #8f2222
        ///black_concrete #080a0f.
        /// </summary>
        internal static string Concrete {
            get {
                return ResourceManager.GetString("Concrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white_terracotta #d3b6a3
        ///orange_terracotta #9f5224
        ///magenta_terracotta #93566b
        ///light_blue_terracotta #6d6a88
        ///yellow_terracotta #b78220
        ///lime_terracotta #677736
        ///pink_terracotta #9f4b4b
        ///gray_terracotta #392a23
        ///light_gray_terracotta #876a62
        ///cyan_terracotta #555a5a
        ///purple_terracotta #744555
        ///blue_terracotta #493a5b
        ///brown_terracotta #4c3223
        ///green_terracotta #4f572e
        ///red_terracotta #913e2f
        ///black_terracotta #271712
        ///terracotta #965d43.
        /// </summary>
        internal static string Terracotta {
            get {
                return ResourceManager.GetString("Terracotta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Test {
            get {
                object obj = ResourceManager.GetObject("Test", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
